spring:
  application:
    name: aspier
  jwt:
    secret-key: OpItImXOyJVzjHN1Eu5mpFybNosqnsEVHQoIRedZ/HY=
  datasource:
    username: irtiza
    password: password
    url: jdbc:postgresql://localhost:5432/aspire_db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  servlet:
    context-path: /api

logging:
  level:
    org:
      springframework:
        security: DEBUG
