spring:
  application:
    name: aspier
  jwt:
    secret-key: OpItImXOyJVzjHN1Eu5mpFybNosqnsEVHQoIRedZ/HY=
  datasource:
    username: irtiza
    password: password
    url: jdbc:postgresql://localhost:5432/aspire_db
    driver-class-name: org.postgresql.Driver
  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
    hibernate:
      ddl-auto: create-drop
server:
  servlet:
    context-path: /api
logging:
  level:
    org:
      springframework:
        security: DEBUG